In [1]:
import sys
sys.path.append('.')

from main import run_pipeline

run_pipeline()

Pipeline complete ✅

In [2]:
import os
os.getcwd()

'/home/ea6ed96c-3368-4e43-a91e-b39087bb62eb/Uber_Price_Predictor'

In [6]:
import pandas as pd

In [108]:
df = pd.read_csv(r"data/processed_uber_data.csv")
df

,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,distance_km,hour,is_rush_hour,minute_per_km,duration_min,surge_multiplier,price
0,2026-01-01 00:00:00,28.174908,-25.712636,28.246000,-25.686186,8.443931,0,False,1.499325,12.660193,1.159951,82.966310
1,2026-01-01 00:05:00,28.290143,-25.716709,28.136902,-25.704071,17.116643,0,False,1.392590,23.836470,1.141242,149.942466
2,2026-01-01 00:10:00,28.246399,-25.732385,28.169328,-25.653550,12.272891,0,False,1.305281,16.019578,1.000908,96.938967
3,2026-01-01 00:15:00,28.219732,-25.689273,28.232656,-25.728102,4.555584,0,False,1.315254,5.991749,1.000416,43.545824
4,2026-01-01 00:20:00,28.131204,-25.702338,28.196418,-25.691214,7.364481,0,False,1.316418,9.694732,1.195490,75.283828
...,...,...,...,...,...,...,...,...,...,...,...,...
9875,2026-02-04 16:50:00,28.124923,-25.659896,28.153863,-25.657530,3.232402,16,True,1.915767,6.192529,1.424938,50.911857
9876,2026-02-04 16:55:00,28.271531,-25.662296,28.290455,-25.674597,2.512518,16,True,2.193594,5.511445,1.588157,49.126660
9877,2026-02-04 17:00:00,28.279502,-25.745319,28.249565,-25.673547,8.656759,17,True,2.009867,17.398931,1.621484,123.427064
9878,2026-02-04 17:05:00,28.289342,-25.719630,28.103891,-25.723043,20.647835,17,True,2.268078,46.830896,1.619781,273.206233
9879,2026-02-04 17:15:00,28.143428,-25.732774,28.151480,-25.701258,3.621030,17,True,2.012223,7.286318,1.463602,56.826675

In [110]:
df = df[ df["distance_km"] <= 20]
df

,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,distance_km,hour,is_rush_hour,minute_per_km,duration_min,surge_multiplier,price
0,2026-01-01 00:00:00,28.174908,-25.712636,28.246000,-25.686186,8.443931,0,False,1.499325,12.660193,1.159951,82.966310
1,2026-01-01 00:05:00,28.290143,-25.716709,28.136902,-25.704071,17.116643,0,False,1.392590,23.836470,1.141242,149.942466
2,2026-01-01 00:10:00,28.246399,-25.732385,28.169328,-25.653550,12.272891,0,False,1.305281,16.019578,1.000908,96.938967
3,2026-01-01 00:15:00,28.219732,-25.689273,28.232656,-25.728102,4.555584,0,False,1.315254,5.991749,1.000416,43.545824
4,2026-01-01 00:20:00,28.131204,-25.702338,28.196418,-25.691214,7.364481,0,False,1.316418,9.694732,1.195490,75.283828
...,...,...,...,...,...,...,...,...,...,...,...,...
9874,2026-02-04 16:45:00,28.263748,-25.700734,28.124661,-25.704762,15.489630,16,True,2.072774,32.106501,1.562523,199.084735
9875,2026-02-04 16:50:00,28.124923,-25.659896,28.153863,-25.657530,3.232402,16,True,1.915767,6.192529,1.424938,50.911857
9876,2026-02-04 16:55:00,28.271531,-25.662296,28.290455,-25.674597,2.512518,16,True,2.193594,5.511445,1.588157,49.126660
9877,2026-02-04 17:00:00,28.279502,-25.745319,28.249565,-25.673547,8.656759,17,True,2.009867,17.398931,1.621484,123.427064
9879,2026-02-04 17:15:00,28.143428,-25.732774,28.151480,-25.701258,3.621030,17,True,2.012223,7.286318,1.463602,56.826675

In [112]:
df["distance_km"].max()

19.996536760514832

In [118]:
df[["distance_km","minute_per_km","duration_min", "surge_multiplier", "price"]] = df[["distance_km","minute_per_km","duration_min", "surge_multiplier","price"]].round(2)
df

C:\Users\Musa_\AppData\Local\Temp\ipykernel_35660\1130003259.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[["distance_km","minute_per_km","duration_min", "surge_multiplier", "price"]] = df[["distance_km","minute_per_km","duration_min", "surge_multiplier","price"]].round(2)

,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,distance_km,hour,is_rush_hour,minute_per_km,duration_min,surge_multiplier,price
0,2026-01-01 00:00:00,28.174908,-25.712636,28.246000,-25.686186,8.44,0,False,1.50,12.66,1.16,82.97
1,2026-01-01 00:05:00,28.290143,-25.716709,28.136902,-25.704071,17.12,0,False,1.39,23.84,1.14,149.94
2,2026-01-01 00:10:00,28.246399,-25.732385,28.169328,-25.653550,12.27,0,False,1.31,16.02,1.00,96.94
3,2026-01-01 00:15:00,28.219732,-25.689273,28.232656,-25.728102,4.56,0,False,1.32,5.99,1.00,43.55
4,2026-01-01 00:20:00,28.131204,-25.702338,28.196418,-25.691214,7.36,0,False,1.32,9.69,1.20,75.28
...,...,...,...,...,...,...,...,...,...,...,...,...
9874,2026-02-04 16:45:00,28.263748,-25.700734,28.124661,-25.704762,15.49,16,True,2.07,32.11,1.56,199.08
9875,2026-02-04 16:50:00,28.124923,-25.659896,28.153863,-25.657530,3.23,16,True,1.92,6.19,1.42,50.91
9876,2026-02-04 16:55:00,28.271531,-25.662296,28.290455,-25.674597,2.51,16,True,2.19,5.51,1.59,49.13
9877,2026-02-04 17:00:00,28.279502,-25.745319,28.249565,-25.673547,8.66,17,True,2.01,17.40,1.62,123.43
9879,2026-02-04 17:15:00,28.143428,-25.732774,28.151480,-25.701258,3.62,17,True,2.01,7.29,1.46,56.83

In [120]:
df["surge_multiplier"].max()

1.8

In [122]:
df[df.isna().any(axis=1)]

Empty DataFrame
Columns: [pickup_datetime, pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, distance_km, hour, is_rush_hour, minute_per_km, duration_min, surge_multiplier, price]
Index: []

In [134]:
df['trip_id'] = range(1001, 1001 + len(df))
df.to_csv(r"C:\Users\Musa_\Documents\Uber_Price_Predictor\data\processed_uber_data.csv", index=False)
df

C:\Users\Musa_\AppData\Local\Temp\ipykernel_35660\2104859012.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['trip_id'] = range(1001, 1001 + len(df))

,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,distance_km,hour,is_rush_hour,minute_per_km,duration_min,surge_multiplier,price,trip_id
0,2026-01-01 00:00:00,28.174908,-25.712636,28.246000,-25.686186,8.44,0,False,1.50,12.66,1.16,82.97,1001
1,2026-01-01 00:05:00,28.290143,-25.716709,28.136902,-25.704071,17.12,0,False,1.39,23.84,1.14,149.94,1002
2,2026-01-01 00:10:00,28.246399,-25.732385,28.169328,-25.653550,12.27,0,False,1.31,16.02,1.00,96.94,1003
3,2026-01-01 00:15:00,28.219732,-25.689273,28.232656,-25.728102,4.56,0,False,1.32,5.99,1.00,43.55,1004
4,2026-01-01 00:20:00,28.131204,-25.702338,28.196418,-25.691214,7.36,0,False,1.32,9.69,1.20,75.28,1005
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9874,2026-02-04 16:45:00,28.263748,-25.700734,28.124661,-25.704762,15.49,16,True,2.07,32.11,1.56,199.08,10712
9875,2026-02-04 16:50:00,28.124923,-25.659896,28.153863,-25.657530,3.23,16,True,1.92,6.19,1.42,50.91,10713
9876,2026-02-04 16:55:00,28.271531,-25.662296,28.290455,-25.674597,2.51,16,True,2.19,5.51,1.59,49.13,10714
9877,2026-02-04 17:00:00,28.279502,-25.745319,28.249565,-25.673547,8.66,17,True,2.01,17.40,1.62,123.43,10715
9879,2026-02-04 17:15:00,28.143428,-25.732774,28.151480,-25.701258,3.62,17,True,2.01,7.29,1.46,56.83,10716